name: Uvicorn App Build Check

on:
  push:
    branches: [ main, develop ] # Trigger on pushes to main or develop
  pull_request:
    branches: [ main, develop ] # Trigger on pull requests targeting main or develop
  workflow_dispatch: # Allows manual triggering from the GitHub UI

jobs:
  build-and-verify:
    name: Verify Python App Build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: '3.10' # Use a specific Python version for consistency
        cache: 'pip' # Cache pip dependencies for faster re-runs

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # Install main application dependencies
        pip install -r requirements.txt
        # Install development dependencies if requirements-dev.txt exists
        # This is where 'uvicorn' would typically be installed
        if [ -f requirements-dev.txt ]; then
          pip install -r requirements-dev.txt
        fi

    - name: Verify application module and 'app' object import
      run: |
        # IMPORTANT: If 'vm_update_tool_server.py' is in a subdirectory (e.g., 'src/'),
        # you might need to adjust the PYTHONPATH or the import statement.
        # Example: if your app is in 'src/vm_update_tool_server.py',
        # you might change to 'PYTHONPATH=src python -c "import vm_update_tool_server; getattr(vm_update_tool_server, 'app')"'.
        
        # This command attempts to:
        # 1. Import the 'vm_update_tool_server' module.
        # 2. Access the 'app' attribute within that module.
        # This verifies that your Python file is syntactically correct and
        # that the 'app' object Uvicorn expects exists and is accessible.
        python -c "import vm_update_tool_server; \
                   getattr(vm_update_tool_server, 'app'); \
                   print('Module vm_update_tool_server and its app object imported successfully!')"

    - name: Verify Uvicorn CLI installation and basic functionality
      run: |
        # This checks if the 'uvicorn' command itself is installed and executable.
        # It's a quick way to confirm that the 'uvicorn' package was installed correctly.
        uvicorn --version
        echo "Uvicorn CLI verified."
